apiVersion: v1
kind: Service
metadata:
  name: lingogame-lb
spec:
  selector:
    app: lingogame-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingogame-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lingogame-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lingogame-service
    spec:
      containers:
        - name: lingogame-service
          image: ${DOCKER_USERNAME}/lingowords:$SEMAPHORE_WORKFLOW_ID
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: JDBC_DATABASE_HOST
              value: "${JDBC_DATABASE_HOST}"
            - name: JDBC_DATABASE_PORT
              value: "${JDBC_DATABASE_PORT}"
            - name: JDBC_DATABASE_NAME
              value: "${JDBC_DATABASE_NAME}"
            - name: JDBC_DATABASE_USERNAME
              value: "${JDBC_DATABASE_USERNAME}"
            - name: JDBC_DATABASE_PASSWORD
              value: "${JDBC_DATABASE_PASSWORD}"
            - name: LINGOWORDS_API
              value: "http://35.195.142.9"
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /highscore
              port: 8080